### ISSUE TITLE
active stream count may return a wrong count when panic

### ISSUE THREAD

**Issue by cch123** [mosn/mosn#1238]
### Environment

- MOSN Version

**Comment by cch123** [comment]
验证：
![image](https://user-images.githubusercontent.com/384546/86551937-14d9fd80-bf79-11ea-9f0e-19d17e05b

```shell
mosn.io/mosn/pkg/proxy.(*downStream).OnReceive.func1()
	/Users/xargin/go/src/mosn.io/mosn/pkg/proxy/downstream.go:359 +0x6f
mosn.io/mosn/pkg/sync.(*workerPool).spawnWorker(0xc000127970, 0xc000152cc0)
	/Users/xargin/go/src/mosn.io/mosn/pkg/sync/workerpool.go:169 +0x5e
created by mosn.io/mosn/pkg/sync.(*workerPool).ScheduleAuto
	/Users/xargin/go/src/mosn.io/mosn/pkg/sync/workerpool.go:149 +0x23b
serverListener 10
serverListener 10
serverListener 10
serverListener 10
serverListener 10
serverListener 10
serverListener 10
serverListener 10
serverListener 10
serverListener 10
```

metrics 计数确实一直没有恢复。

**Comment by cch123** [comment]
修复测试

```go
goroutine 60 [running]:
runtime/debug.Stack(0xc00006d530, 0x4e30e80, 0x529cda0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
mosn.io/mosn/pkg/proxy.(*downStream).OnReceive.func1.1(0xc0004fe000, 0x1)
	/Users/xargin/go/src/mosn.io/mosn/pkg/proxy/downstream.go:353 +0x6e
panic(0x4e30e80, 0x529cda0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
mosn.io/mosn/pkg/proxy.(*downStream).OnReceive.func1.2()
	/Users/xargin/go/src/mosn.io/mosn/pkg/proxy/downstream.go:363 +0x39
sync.(*Once).doSlow(0x5e2eb00, 0x514c398)
	/usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
mosn.io/mosn/pkg/proxy.(*downStream).OnReceive.func1()
	/Users/xargin/go/src/mosn.io/mosn/pkg/proxy/downstream.go:362 +0x3ce
mosn.io/mosn/pkg/sync.(*workerPool).spawnWorker(0xc0002d87f0, 0xc00028e210)
	/Users/xargin/go/src/mosn.io/mosn/pkg/sync/workerpool.go:169 +0x5e
created by mosn.io/mosn/pkg/sync.(*workerPool).ScheduleAuto
	/Users/xargin/go/src/mosn.io/mosn/pkg/sync/workerpool.go:149 +0x23b
serverListener 6
serverListener 5
serverListener 7
serverListener 1
serverListener 0
```

在 panic 一次之后，请求完毕之后会恢复到 0，不会有问题。

**Comment by taoyuanyuan** [comment]
这样验证是不完整的，只是证明了metric没有问题。
还有trace，log，giveStream等，在这些能力开启的情况下，cleanStream提前结束会有问题吗？

**Comment by cch123** [comment]
补一下另几个流程的结果：

panic 的时候：

**trace disable 的情况：**

span 为空，warning 日志，
```
2020-07-06 19:42:22,179 [WARN] [5,0a0fe9201594035742179769122561] [proxy] [downstream] trace span is null
```

**trace enable 的情况：**
正常执行

**writeLog 的情况：**

```
2020-07-06 19:54:16,719 [DEBUG] [3,0a0fe9201594036456719530024203] [proxy] [downstream] timeout info: {GlobalTimeout:1m0s TryTimeout:0s}
2020-07-06 19:54:16,719 [DEBUG] [10,0a0fe9201594036456719529524203] [proxy] [upstream] OnReceive headers: HTTP/1.1 404 Not Found
Server: Jetty(9.4.17.v20190418)
Date: Mon, 06 Jul 2020 11:54:16 GMT
Content-Type: text/html;charset=iso-8859-1
Content-Length: 317
Cache-Control: must-revalidate,no-cache,no-store
X-Mosn-Status: 404

```

开启后正常执行

**giveStream** 
每一步都有判空，所以也正常执行完毕了

**Comment by taoyuanyuan** [comment]
以防万一，比如后面又加了其他逻辑可能导致问题。
给cleanStream也加一个defer？

**Comment by cch123** [comment]
在 recover 里再 panic 么。。那也只能拦住 defer 后面的，
要是 panic 在前面

**Comment by taoyuanyuan** [comment]
cleanStream是再recover里面的，他如果再panic了，他自己的recover可以兜住吧，不会让整个程序panic？

**Comment by taoyuanyuan** [comment]
```
package main

import (
	"fmt"
	"time"
)

func test() {
	defer func() {
		if err := recover(); err != nil {
			cleanStream()
		}
	}()
	panic(1)
}

func cleanStream() {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println("test2 panic")
		}
	}()
	panic(1)
}

func main() {
	go test()
	time.Sleep(time.Second)
	fmt.Print("hello")
}
```
如果cleanStream有panic，我理解不会对main()程序造成影响。

**Comment by cch123** [comment]
@taoyuanyuan ，https://github.com/mosn/mosn/pull/1254/commits/d40a981f45677e1f1819a5972af2c40ea27bb208#diff-ba11a00bb14720d45706e6dee657a6aeR196
