### ISSUE TITLE
部署 Istio 与 MOSN 启动后健康检查失败

### ISSUE THREAD

**Issue by bobtthp** [mosn/mosn#2021]
### mson 启动时出现非法内存访问

![113CF42B-92CB-4ECE-BBC8-AC170E79D1AF](https://user-images.githubusercontent.com/23113152/165276624-25c02dc3-7ef4-4e88-94f3-8052cfa896a0.png)

### Environment

k8s version:  1.18.20
istio version: 1.10.6

部署方式按照：
![image](https://user-images.githubusercontent.com/23113152/165276755-510db431-2827-4480-a1b0-bd6f649170c5.png)

- MOSN Version

mson version: 1.0.0
编译mson golang version:  1.18

### Logs

日志如下：
2022-04-26T09:54:45.586778Z     info    FLAG: --concurrency="0"
2022-04-26T09:54:45.586805Z     info    FLAG: --domain="istio-system.svc.cluster.local"
2022-04-26T09:54:45.586811Z     info    FLAG: --help="false"
2022-04-26T09:54:45.586819Z     info    FLAG: --log_as_json="false"
2022-04-26T09:54:45.586823Z     info    FLAG: --log_caller=""
2022-04-26T09:54:45.586826Z     info    FLAG: --log_output_level="default:info"
2022-04-26T09:54:45.587007Z     info    FLAG: --log_rotate=""
2022-04-26T09:54:45.587035Z     info    FLAG: --log_rotate_max_age="30"
2022-04-26T09:54:45.587039Z     info    FLAG: --log_rotate_max_backups="1000"
2022-04-26T09:54:45.587059Z     info    FLAG: --log_rotate_max_size="104857600"
2022-04-26T09:54:45.587093Z     info    FLAG: --log_stacktrace_level="default:none"
2022-04-26T09:54:45.587195Z     info    FLAG: --log_target="[stdout]"
2022-04-26T09:54:45.587222Z     info    FLAG: --meshConfig="./etc/istio/config/mesh"
2022-04-26T09:54:45.587226Z     info    FLAG: --outlierLogPath=""
2022-04-26T09:54:45.587229Z     info    FLAG: --proxyComponentLogLevel="misc:error"
2022-04-26T09:54:45.587290Z     info    FLAG: --proxyLogLevel="warning"
2022-04-26T09:54:45.587294Z     info    FLAG: --serviceCluster="istio-ingressgateway"
2022-04-26T09:54:45.587297Z     info    FLAG: --stsPort="0"
2022-04-26T09:54:45.587299Z     info    FLAG: --templateFile=""
2022-04-26T09:54:45.587346Z     info    FLAG: --tokenManagerPlugin="GoogleTokenExchange"
2022-04-26T09:54:45.587360Z     info    Version 1.10-dev-fd053c6165d21105d66dac6e3d0649db2dde5b86-dirty-Modified
2022-04-26T09:54:45.587578Z     info    Proxy role      ips=[10.0.2.150] type=router id=istio-ingressgateway-65884d6868-hrxrm.istio-system domain=istio-system.svc.cluster.local
2022-04-26T09:54:45.587703Z     info    Apply mesh config from file defaultConfig:
  binaryPath: /usr/local/bin/mosn
  discoveryAddress: istiod.istio-system.svc:15012
  proxyMetadata: {}
  tracing:
    zipkin:
      address: zipkin.istio-system:9411
enablePrometheusMerge: true
rootNamespace: istio-system
trustDomain: cluster.local
2022-04-26T09:54:45.588922Z     info    Effective config: binaryPath: /usr/local/bin/mosn
concurrency: 0
configPath: ./etc/istio/proxy
controlPlaneAuthPolicy: MUTUAL_TLS
discoveryAddress: istiod.istio-system.svc:15012
drainDuration: 45s
parentShutdownDuration: 60s
proxyAdminPort: 15000
proxyMetadata: {}
serviceCluster: istio-ingressgateway
statNameLength: 189
statusPort: 15020
terminationDrainDuration: 5s
tracing:
  zipkin:
    address: zipkin.istio-system:9411

2022-04-26T09:54:45.588941Z     info    JWT policy is first-party-jwt
2022-04-26T09:54:45.588990Z     info    Pilot SAN: [istiod.istio-system.svc]
2022-04-26T09:54:45.588994Z     info    CA Endpoint istiod.istio-system.svc:15012, provider Citadel
2022-04-26T09:54:45.589118Z     info    Using CA istiod.istio-system.svc:15012 cert with certs: var/run/secrets/istio/root-cert.pem
2022-04-26T09:54:45.589337Z     info    citadelclient   Citadel client using custom root cert: istiod.istio-system.svc:15012
2022-04-26T09:54:45.617274Z     info    ads     All caches have been synced up in 32.123969ms, marking server ready
2022-04-26T09:54:45.617723Z     info    sds     SDS server for workload certificates started, listening on "./etc/istio/proxy/SDS"
2022-04-26T09:54:45.617808Z     info    xdsproxy        Initializing with upstream address "istiod.istio-system.svc:15012" and cluster "Kubernetes"
2022-04-26T09:54:45.618105Z     info    sds     Start SDS grpc server
2022-04-26T09:54:45.618243Z     info    Opening status port 15020
2022-04-26T09:54:45.819531Z     info    cache   generated new workload certificate      latency=201.604261ms ttl=23h59m59.180478243s
2022-04-26T09:54:45.819694Z     info    cache   Root cert has changed, start rotating root cert
2022-04-26T09:54:45.819810Z     info    ads     XDS: Incremental Pushing:0 ConnectedEndpoints:0 Version:
2022-04-26T09:54:45.819898Z     info    cache   returned workload trust anchor from cache       ttl=23h59m59.180104553s
2022-04-26T09:54:47.620160Z     info    Starting proxy agent
2022-04-26T09:54:47.620353Z     info    Epoch 0 starting
2022-04-26T09:54:47.625293Z     info    Envoy command: [-c etc/istio/proxy/envoy-rev0.json --restart-epoch 0 --drain-time-s 45 --drain-strategy immediate --parent-shutdown-time-s 60 --service-cluster istio-ingressgateway --service-node router~10.0.2.150~istio-ingressgateway-65884d6868-hrxrm.istio-system~istio-system.svc.cluster.local --local-address-ip-version v4 --bootstrap-version 3 --disable-hot-restart --log-format %Y-%m-%dT%T.%fZ%l      envoy %n        %v -l warning --component-log-level misc:error]
2022-04-26 09:54:47,650 [INFO] register a new handler maker, name is default, is default: true
2022-04-26 09:54:47,660 [INFO] [admin server] [register api] register a new api /server_info
2022-04-26 09:54:47,660 [INFO] [admin server] [register api] register a new api /config_dump
2022-04-26 09:54:47,660 [INFO] [config] processor added to configParsedCBMaps
2022-04-26 09:54:47,663 [INFO] [network] [ register pool factory] register protocol: Http1 factory
2022-04-26 09:54:47,663 [INFO] [network] [ register pool factory] register protocol: Http2 factory
2022-04-26 09:54:47,671 [INFO] [mosn start] create an empty mosn structure
2022-04-26 09:54:47,671 [INFO] [stagemanager] state changed to 1
2022-04-26 09:54:47,671 [INFO] [network] [ register pool factory] register protocol: bolt factory
2022-04-26 09:54:47,671 [INFO] [network] [ register pool factory] register protocol: boltv2 factory
2022-04-26 09:54:47,671 [INFO] [network] [ register pool factory] register protocol: dubbo factory
2022-04-26 09:54:47,671 [INFO] [network] [ register pool factory] register protocol: dubbo-thrift factory
2022-04-26 09:54:47,671 [INFO] [network] [ register pool factory] register protocol: tars factory
2022-04-26 09:54:47,671 [INFO] load config from :  etc/istio/proxy/envoy-rev0.json
2022-04-26 09:54:47,672 [INFO] parameters parsed stage cost: 1.2702ms
2022-04-26 09:54:47,672 [INFO] [stagemanager] state changed to 2
2022-04-26 09:54:47,673 [ERROR] write pid file error: open /etc/istio/logs/mosn.pid: no such file or directory
2022-04-26 09:54:47,673 [INFO] [mosn] [init tracing] disable tracing
2022-04-26 09:54:47,674 [INFO] [server] [reconfigure] not reconfigure: dial unix /etc/istio/proxy/reconfig.sock: connect: no such file or directory
2022-04-26 09:54:47,674 [INFO] [mosn] [NewMosn] new mosn created
2022-04-26 09:54:47,674 [INFO] [mosn start] init the members of the mosn
2022-04-26 09:54:47,674 [INFO] [mosn start] mosn init cluster structures
2022-04-26 09:54:47,674 [WARN] [config] [parse cluster] No Cluster provided in cluster config
2022-04-26 09:54:47,674 [INFO] [mosn start] mosn init server structures
2022-04-26 09:54:47,674 [INFO] init stage cost: 1.448423ms
2022-04-26 09:54:47,674 [INFO] [mosn start] mosn start xds client
2022-04-26 09:54:47,685 [WARN] only random lbPoliy supported, convert to random
2022-04-26 09:54:47,685 [WARN] only random lbPoliy supported, convert to random
2022-04-26 09:54:47,685 [WARN] only random lbPoliy supported, convert to random
2022-04-26 09:54:47,685 [WARN] only random lbPoliy supported, convert to random
2022-04-26 09:54:47,685 [WARN] only random lbPoliy supported, convert to random
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14795aa]

goroutine 1 [running]:
github.com/modern-go/reflect2.(*frozenConfig).Type2(0x21af160, {0x273f210, 0x2122ac0})
        /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/reflect2.go:157 +0x4a
github.com/modern-go/reflect2.(*UnsafeMapType).Key(0xc000171440)
        /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:53 +0x49
github.com/json-iterator/go.decoderOfMap(0xc00015ad78, {0x2736aa0?, 0xc000171440})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect_map.go:14 +0xe5
github.com/json-iterator/go._createDecoderOfType(0xc00015ad78, {0x2736aa0?, 0xc000171440})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:182 +0x2c8
github.com/json-iterator/go.createDecoderOfType(0xc00015ad78, {0x2736aa0, 0xc000171440})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:142 +0xdf
github.com/json-iterator/go.decoderOfType(0xc00015ad78, {0x2736aa0, 0xc000171440})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:124 +0x45
github.com/json-iterator/go.(*frozenConfig).DecoderOf(0xc0001e7ae0, {0x2736b40, 0xc000131bf0})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:114 +0x108
github.com/json-iterator/go.(*Iterator).ReadVal(0xc0008fbcb0, {0x20d04a0, 0xc00051b6b8})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/reflect.go:72 +0xe5
github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc0001e7ae0, {0xc000485680?, 0xc0002018f0?, 0x0?}, {0x20d04a0, 0xc00051b6b8})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.10/config.go:348 +0xa5
mosn.io/mosn/istio/istio1106/xds/conv.toMap({0x20d3920, 0xc0002018f0})
        /data/dev/mosn/istio/istio1106/xds/conv/convert_listener.go:610 +0x86
mosn.io/mosn/istio/istio1106/xds/conv.convertFilters({0xc00051b090, 0x1, 0x1}, 0x118000?, 0xb6?)
        /data/dev/mosn/istio/istio1106/xds/conv/convert_listener.go:591 +0xed
mosn.io/mosn/istio/istio1106/xds/conv.convertFilterChains(0xc000142420, 0x0, 0x2?)
        /data/dev/mosn/istio/istio1106/xds/conv/convert_listener.go:488 +0x293
mosn.io/mosn/istio/istio1106/xds/conv.ConvertListenerConfig(0xc000142420, 0x24c39b0?)
        /data/dev/mosn/istio/istio1106/xds/conv/convert_listener.go:149 +0x7d9
mosn.io/mosn/istio/istio1106/xds/conv.(*xdsConverter).ConvertAddOrUpdateListeners(0xc0008ed900, {0xc000268dc0, 0x2, 0x2})
        /data/dev/mosn/istio/istio1106/xds/conv/update.go:88 +0x1a5
mosn.io/mosn/istio/istio1106/xds.(*AdsConfig).loadStaticResources(0xc000201180, 0xc0000f4620)
        /data/dev/mosn/istio/istio1106/xds/ads_config.go:267 +0x10c
mosn.io/mosn/istio/istio1106/xds.unmarshalResources({0xc00020f400?, 0xc000132550?, 0x7fee08303a08?}, {0xc0006ce000, 0x1a4f, 0x1a80})
        /data/dev/mosn/istio/istio1106/xds/parse_config.go:72 +0x294
mosn.io/mosn/istio/istio1106/xds.UnmarshalResources({0xc00020f400?, 0xc00000e2a0?, 0x2491ef5?}, {0xc0006ce000?, 0x24c6b57?, 0x0?})
        /data/dev/mosn/istio/istio1106/xds/parse_config.go:43 +0x27
mosn.io/mosn/pkg/istio.ParseAdsConfig(...)
        /data/dev/mosn/pkg/istio/factory.go:34
mosn.io/mosn/pkg/istio.NewAdsClient(0x0?)
        /data/dev/mosn/pkg/istio/xds.go:45 +0x52
mosn.io/mosn/pkg/mosn.(*Mosn).StartXdsClient(0xc000148090)
        /data/dev/mosn/pkg/mosn/mosn.go:313 +0x5a
mosn.io/mosn/pkg/mosn.DefaultPreStartStage({0x272c4c8?, 0xc000148090})
        /data/dev/mosn/pkg/mosn/default_stages.go:49 +0x45
mosn.io/mosn/pkg/stagemanager.(*StageManager).runPreStartStage(0x36e7960)
        /data/dev/mosn/pkg/stagemanager/stage_manager.go:239 +0x86
mosn.io/mosn/pkg/stagemanager.(*StageManager).Run(0x36e7960)
        /data/dev/mosn/pkg/stagemanager/stage_manager.go:304 +0x39
mosn.io/mosn/pkg/stagemanager.(*StageManager).RunAll(0x36e7960)
        /data/dev/mosn/pkg/stagemanager/stage_manager.go:579 +0x1e
main.glob..func1(0xc000220840)
        /data/dev/mosn/cmd/mosn/main/control.go:210 +0x792
main.newMosnApp.func1(0xc000220840?)
        /data/dev/mosn/cmd/mosn/main/mosn.go:113 +0x53
github.com/urfave/cli.HandleAction({0x213bac0?, 0xc00067e1f0?}, 0xc0000c0350?)
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0xa8
github.com/urfave/cli.(*App).Run(0xc00002a380, {0xc0000c0340, 0x1a, 0x1a})
        /root/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:285 +0x818
main.main()
        /data/dev/mosn/cmd/mosn/main/mosn.go:88 +0x3f
2022-04-26T09:54:47.694637Z     error   Epoch 0 exited with error: exit status 2
2022-04-26T09:54:47.694672Z     info    No more active epochs, terminating

**Comment by nejisama** [comment]
几个问题没有描述清楚，再说一下？
1. 部署的哪个pod出现的问题啊？
2. 用这种方式更新的镜像，就是单纯的重新编译了一个mosn二进制，还是改了什么内容？如果直接用提供的原始镜像是不是也是同样的问题？

**Comment by bobtthp** [comment]
确实是我编译的问题，使用容器镜像golang 版本1.14.13编译没有加goproxy，所以我使用本地1.18编译的后出现了这个问题。
刚刚使用1.14.13版本重新编译，启动正常了。

**Comment by bobtthp** [comment]
确实是我编译的问题，使用容器镜像golang 版本1.14.13编译没有加goproxy，所以我使用本地1.18编译的后出现了这个问题。
刚刚使用1.14.13版本重新编译，启动正常了。
